### ISSUE TITLE
truffle compile doesn't work

### ISSUE THREAD

**Issue by trancept** [iExecBlockchainComputing/PoCo#41]
After a fresh git clone, then npm install, the command :
$ ./node_modules/.bin/truffle compile
Output:
```
SyntaxError: Unexpected token < in JSON at position 77187
    at JSON.parse (<anonymous>)
    at /home/ben/src/PoCo/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-compile/profiler.js:80:1
    at /home/ben/src/PoCo/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-compile/~/async/dist/async.js:1126:1
    at /home/ben/src/PoCo/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-compile/~/async/dist/async.js:473:1
    at iteratorCallback (/home/ben/src/PoCo/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-compile/~/async/dist/async.js:1050:1)
    at /home/ben/src/PoCo/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-compile/~/async/dist/async.js:958:1
    at /home/ben/src/PoCo/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-compile/~/async/dist/async.js:1123:1
    at /home/ben/src/PoCo/node_modules/truffle/build/webpack:/~/truffle-core/~/truffle-compile/profiler.js:73:1
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:525:3)
```
npm 6.1.0
node v9.11.1

**Comment by trancept** [comment]
That's come from bad file in "build/contracts", removing build solved the issue.
So maybe you could remove "build" from the repo.

**Comment by branciard** [comment]
yes we will remove it on  the next release : https://github.com/iExecBlockchainComputing/PoCo/issues/40
